#!/usr/bin/env python
"""Generate (once) the firmware update signing key and emit the public half.

The self-update path (0.18) trusts an ECDSA-P256 signature over the firmware
hash, NOT GitHub's TLS certificate. This script creates the PRIVATE key that
release.py signs with, and writes the matching PUBLIC key into the firmware
source (src/update_pubkey.h) so the printer can verify.

WHERE THE PRIVATE KEY LIVES. Outside the repo, by design: in the repo it would
be public, and a public signing key is no key at all. Default location is
%USERPROFILE%\\.tinymaker\\fw_signing_key.pem (override with the env var
TINYMAKER_SIGNING_KEY). release.py reads the same path/var.

BACK IT UP, KEEP IT SECRET. Lose it and you can never sign another update (the
fleet's public key no longer matches). Leak it and anyone can push firmware to
every printer. Treat it like the GitHub token.

Run once (PlatformIO penv python):
  ~/.platformio/penv/Scripts/python.exe scripts/dev/gen_fw_signing_key.py

Re-running refuses to overwrite an existing key (that would orphan every
printer already carrying the old public key). Pass --rotate only if you really
mean to mint a NEW root of trust - every printer then needs a manual reflash.
"""
import os
import sys
from pathlib import Path

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ec

REPO_ROOT = Path(__file__).resolve().parents[2]
PUBKEY_HEADER = REPO_ROOT / "src" / "update_pubkey.h"


def key_path() -> Path:
    env = os.environ.get("TINYMAKER_SIGNING_KEY")
    if env:
        return Path(env)
    return Path.home() / ".tinymaker" / "fw_signing_key.pem"


def write_header(pub_pem: str) -> None:
    body = pub_pem.strip("\n")
    text = (
        "// Public key for firmware self-update signature verification (0.18).\n"
        "//\n"
        "// GENERATED by scripts/dev/gen_fw_signing_key.py - do not edit by hand.\n"
        "// The matching PRIVATE key lives OUTSIDE the repo (see that script) and\n"
        "// release.py signs every published firmware with it. The printer accepts\n"
        "// an update only if its ECDSA-P256 signature verifies against this key,\n"
        "// so the transport no longer depends on GitHub's TLS certificate - which\n"
        "// is what a per-region certificate authority change broke (Garry, 09-22).\n"
        "#pragma once\n\n"
        "static const char UPDATE_PUBKEY_PEM[] =\n"
        'R"PEM(' + body + ')PEM";\n'
    )
    PUBKEY_HEADER.write_text(text, encoding="utf-8", newline="\n")


def main() -> int:
    rotate = "--rotate" in sys.argv
    path = key_path()

    if path.exists() and not rotate:
        # Do not silently mint a new root of trust: re-emit the header from the
        # existing key so a fresh checkout can be made to compile without
        # touching the key itself.
        priv = serialization.load_pem_private_key(path.read_bytes(), password=None)
        if not isinstance(priv.curve, ec.SECP256R1):
            print(f"ERROR: {path} is not an ECDSA P-256 key.", file=sys.stderr)
            return 1
        pub_pem = priv.public_key().public_bytes(
            serialization.Encoding.PEM,
            serialization.PublicFormat.SubjectPublicKeyInfo,
        ).decode()
        write_header(pub_pem)
        print(f"Key already present: {path}")
        print(f"Public key re-written to {PUBKEY_HEADER}")
        print("(pass --rotate to mint a NEW key - every printer then needs a manual reflash)")
        return 0

    priv = ec.generate_private_key(ec.SECP256R1())
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(
        priv.private_bytes(
            serialization.Encoding.PEM,
            serialization.PrivateFormat.PKCS8,
            serialization.NoEncryption(),
        )
    )
    try:
        os.chmod(path, 0o600)
    except OSError:
        pass

    pub_pem = priv.public_key().public_bytes(
        serialization.Encoding.PEM,
        serialization.PublicFormat.SubjectPublicKeyInfo,
    ).decode()
    write_header(pub_pem)

    print(f"Private key written to {path}  (BACK IT UP, KEEP IT SECRET)")
    print(f"Public key written to  {PUBKEY_HEADER}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
