// Public key for firmware self-update signature verification (0.18).
//
// GENERATED by scripts/dev/gen_fw_signing_key.py - do not edit by hand.
// The matching PRIVATE key lives OUTSIDE the repo (see that script) and
// release.py signs every published firmware with it. The printer accepts
// an update only if its ECDSA-P256 signature verifies against this key,
// so the transport no longer depends on GitHub's TLS certificate - which
// is what a per-region certificate authority change broke (Garry, 09-22).
#pragma once

static const char UPDATE_PUBKEY_PEM[] =
R"PEM(-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAERpGR+xKDcpco596DhXGbwVpxjy96
gP0Jag+2s095j4XPkY8jbAZDJN1ZOuwomB79ouLYxt4ZDn2GNqlrzjcqlg==
-----END PUBLIC KEY-----)PEM";
